package org.acme.rest.dealapp

data class CompanyContactParticipant(
    val assignments: List<String>,
    val author: String,
    val comment: Any,
    val company: String,
    val createDateTime: String,
    val decisionRole: Any,
    val department: Any,
    val draft: Any,
    val endDate: Any,
    val firstName: String,
    val fullName: String,
    val id: String,
    val isActive: Boolean,
    val isEdsSigner: Boolean,
    val isMainEdsSigner: Any,
    val job: String,
    val lastName: String,
    val manager: Any,
    val middleName: String,
    val modifiedDateTime: Any,
    val modifier: Any,
    val participantType: String,
    val priorityNumber: Any,
    val startDate: Any,
    val userContact: String,
    val userEmail: String,
    val userPhone: String,
    val verificationType: String,
    val verificationValue: Any
)